# frozen_string_literal: true

source "https://rubygems.org"

gem "pry", git: "https://github.com/pry/pry.git", ref: "899684c3ba24156e0ca3853b74ac58c276a14379" # https://github.com/pry/pry/issues/2097

group :test do
  gem "rspec"
end
